---
# wsl ansible-playbook -i inventory playbook.yml
- name: Установка ELK на Ubuntu 22.04
  hosts: all
  become: yes

  roles:
    - role: common
    - role: elasticsearch
    - role: kibana
    - role: filebeat
    - role: logstash


